//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastTunnel.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TunnelResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TunnelResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FastTunnel.Core.TunnelResource", typeof(TunnelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ForwardDisabled {
            get {
                return ResourceManager.GetString("ForwardDisabled", resourceCulture);
            }
        }
        
        public static string NoTunnel {
            get {
                return ResourceManager.GetString("NoTunnel", resourceCulture);
            }
        }
        
        public static string Page_HostRequired {
            get {
                return ResourceManager.GetString("Page_HostRequired", resourceCulture);
            }
        }
        
        public static string Page_NoSite {
            get {
                return ResourceManager.GetString("Page_NoSite", resourceCulture);
            }
        }
        
        public static string Page_NotAccessIps {
            get {
                return ResourceManager.GetString("Page_NotAccessIps", resourceCulture);
            }
        }
        
        public static string Page_NotFund {
            get {
                return ResourceManager.GetString("Page_NotFund", resourceCulture);
            }
        }
        
        public static string Page_Offline {
            get {
                return ResourceManager.GetString("Page_Offline", resourceCulture);
            }
        }
        
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        public static string TunnelLlist {
            get {
                return ResourceManager.GetString("TunnelLlist", resourceCulture);
            }
        }
    }
}
